language: python
sudo: false

python:
  - "3.5"

env:
  - DJANGO=1.10.5

branches:
  only:
    - master

install:
  - pip install tox coverage codecov
  - pip install -r requirements.txt

before_install:
  - export DJANGO_SETTINGS_MODULE=frisor.settings
  - export SECRET_KEY='This is secret'

script:
  - cd frisor
  - python manage.py test


after_success:
  - coverage combine
  - codecov